import { Metadata } from 'next';
import { MarketingShell, PageHeading } from '@/components/marketing/MarketingShell';
import { absoluteUrl } from '@/lib/site';

export const metadata: Metadata = { title: 'Public demo privacy boundary | Veloxis', description: 'The public Veloxis evaluation uses synthetic data only and does not accept client personal information.', alternates: { canonical: absoluteUrl('/privacy') } };

export default function PrivacyPage() {
  return <MarketingShell><PageHeading eyebrow="Public demo privacy" title="Synthetic scenarios only."><p>The public Veloxis pilot is a product evaluation environment, not a client-record system.</p></PageHeading><section className="mx-auto grid max-w-6xl gap-5 px-5 py-14 md:grid-cols-2 md:px-8"><article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-7"><h2 className="text-xl font-black text-emerald-950">What the public demo does</h2><ul className="mt-4 space-y-3 leading-7 text-emerald-900"><li>Uses a fictional household and synthetic dollar values.</li><li>Runs retirement scenario calculations in the browser.</li><li>Lets evaluators change defined scenario levers for the fictional case.</li></ul></article><article className="rounded-2xl border border-rose-200 bg-rose-50 p-7"><h2 className="text-xl font-black text-rose-950">What you must not enter</h2><ul className="mt-4 space-y-3 leading-7 text-rose-900"><li>Client names, email addresses, or physical addresses.</li><li>Account, policy, Social Security, tax, or identification numbers.</li><li>Statements, documents, uploads, or any personally identifiable financial data.</li></ul></article></section><section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-4xl px-5 py-12 md:px-8"><h2 className="text-2xl font-black tracking-tight text-[#111c3d]">A deliberate first-pilot boundary</h2><p className="mt-4 leading-8 text-slate-600">Veloxis does not offer account aggregation, cloud client storage, user authentication, document upload, or automated financial advice in this public pilot. Any future expansion involving customer data requires separate security, privacy, consent, deletion/export, and compliance design.</p></div></section></MarketingShell>;
}

